DROP TABLE IF EXISTS BOOKINGS;

CREATE TABLE BOOKINGS (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    ARRIVAL_DATE DATE NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    BOOKING_UUID VARCHAR(36) NOT NULL
);
